# Generated by Django 5.1.1 on 2025-03-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subspot', '0002_user_age_monthlyexpense_subscription_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='month_name',
            field=models.CharField(choices=[('January', 'january'), ('February', 'february'), ('March', 'march'), ('April', 'april'), ('May', 'may'), ('June', 'june'), ('July', 'july'), ('August', 'august'), ('September', 'september'), ('October', 'october'), ('November', 'november'), ('December', 'december')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_autorenew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_shareable',
            field=models.BooleanField(default=True),
        ),
    ]
