# Generated by Django 5.1.1 on 2025-03-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subspot', '0004_alter_monthlyexpense_month_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='duration',
            field=models.CharField(default='', max_length=255),
        ),
    ]
