# Generated by Django 5.1.7 on 2025-03-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subspot', '0007_alter_listing_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
